### ISSUE TITLE
Does not compile on armv7

### ISSUE THREAD

**Issue by TimB87** [epilys/bb#17]
Hi,

bb fails to compile on armv7 (Raspberry Pi 4 on 32 bit kernel) due to mismatched types in src/ui.rs:

```
Running `/usr/bin/sccache rustc --crate-name bb --edition=2018 src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C opt-level=z -C panic=abort -C lto -C codegen-units=1 -C metadata=b23183f680d3f447 -C extra-filename=-b23183f680d3f447 --out-dir /home/pkgmk/work/bb/src/bb-0.4.0/target/release/deps -L dependency=/home/pkgmk/work/bb/src/bb-0.4.0/target/release/deps --extern cassowary=/home/pkgmk/work/bb/src/bb-0.4.0/target/release/deps/libcassowary-4a7ad7d23a126827.rlib --extern crossbeam=/home/pkgmk/work/bb/src/bb-0.4.0/target/release/deps/libcrossbeam-b88bd576ff9b908c.rlib --extern libc=/home/pkgmk/work/bb/src/bb-0.4.0/target/release/deps/liblibc-6b574da7dc34fe2b.rlib --extern nix=/home/pkgmk/work/bb/src/bb-0.4.0/target/release/deps/libnix-b588c22e34e6da26.rlib --extern signal_hook=/home/pkgmk/work/bb/src/bb-0.4.0/target/release/deps/libsignal_hook-5ac681d4caa4614b.rlib --extern termion=/home/pkgmk/work/bb/src/bb-0.4.0/target/release/deps/libtermion-ea710c8905c296d5.rlib --extern unicode_segmentation=/home/pkgmk/work/bb/src/bb-0.4.0/target/release/deps/libunicode_segmentation-d275c2fd57e41c5a.rlib`
error[E0308]: mismatched types
  --> src/ui.rs:92:54
   |
92 |                 libc::getpwuid_r(pw_uid, &mut pwent, buffer.as_mut_ptr(), 16384, &mut pwentp);
   |                                                      ^^^^^^^^^^^^^^^^^^^ expected `u8`, found `i8`
   |
   = note: expected raw pointer `*mut u8`
              found raw pointer `*mut i8`

error: aborting due to previous error
```

**Comment by epilys** [comment]
Hello, thank you for your report! I closed this because I was able to compile with 

```shell
cross build --target armv7-unknown-linux-gnueabihf
```

([cross](https://github.com/rust-embedded/cross)) for cross-compilation and it compiled successfully. If you still can't compile it or there is another problem please post an update :)

**Comment by TimB87** [comment]
Hi @epilys! Thanks for the response!

I mean, I tried native compilation on armv7, so this is a work around but not really a fix to where it was failing for me.
Not trying to sound bitchy, but cross is too much of a jump for me to setup to even try. 

IMO, the ticket could stay opened, but it's up to you to decide. I'd love to run this on my Pies :) but I just lack the time to dig into it myself, that's why i opened it.

edit: Doh! :clown_face:  Should've paid more attention earlier, sorry! Just realized a691efe461c745845a2d685637c27dbd976d91a9 actually implements a fix :) Thanks!
Compiled fine and works like it's supposed to :tada:

**Comment by epilys** [comment]
Oh yeah I see why my reply was confusing, I understand completely. Thank you as well!
