### ISSUE TITLE
RAM is full but it's not

### ISSUE THREAD

**Issue by RustemB** [epilys/bb#18]
It shows that RAM is full, it's might be bug or not?
![image](https://user-images.githubusercontent.com/25725953/97431059-92b48100-193b-11eb-8162-d5480fb38bbb.png)
also, will be cool if you show percent of CPU

**Comment by whoizit** [comment]
same for me
> also, will be cool if you show percent of CPU

and RAM %

**Comment by whoizit** [comment]
also SWAP bar is missing

**Comment by whoizit** [comment]
incorrect view RAM load
![2020-10-28_15:09:54_738x36_grim](https://user-images.githubusercontent.com/359276/97434207-b7a2f700-192f-11eb-8c2f-0e32c38bd0de.png)
![2020-10-28_15:10:05_564x60_grim](https://user-images.githubusercontent.com/359276/97434201-b5d93380-192f-11eb-9b0b-cd811334e44a.png)

**Comment by RustemB** [comment]
https://github.com/epilys/bb/blob/6de5d6ddc75dd92aad9102192cefa73debe939d1/src/components/kernel.rs#L522
you probably should use crate for work with system memory

**Comment by RustemB** [comment]
You have a logical error
You using `MemFree` instead of `MemAvailable` from `/proc/meminfo`

**Comment by RustemB** [comment]
https://github.com/epilys/bb/blob/fb8666980f6f350e7bbc97c0bf74391391916a52/src/components/kernel.rs#L539
here need to add `.next()` for `MemAvailable`

**Comment by whoizit** [comment]
something like that
```
fn get_mem_info() -> (usize, usize) {
    let mut file = File::open("/proc/meminfo").unwrap();
    let mut res = String::with_capacity(2048);
    file.read_to_string(&mut res).unwrap();

    let mut mem_total = 0usize;
    let mut mem_available = 0usize;

    for (index, line) in res.lines().enumerate() {
        match index {
            0 => mem_total = line.split_whitespace().skip(1).next().unwrap().parse().unwrap_or(0),
            2 => mem_available = line.split_whitespace().skip(1).next().unwrap().parse().unwrap_or(0),
            _ => (),
        };  
    }   
    (mem_available, mem_total)
}
```

**Comment by epilys** [comment]
Thank you for catching this!
