### ISSUE TITLE
184467440737095520% CPU usage :^)

### ISSUE THREAD

**Issue by TimB87** [epilys/bb#24]
Hi @epilys 

I am just seeing this, not sure if before I just didn't notice..? I can assure this is just a normal i5-3570k :laughing: 

 ![184467440737095520%](https://i.imgur.com/3vnMZrU.png)

**Comment by bl-ue** [comment]
Hmm, that's equal to `2**64/100`.  Something to do with overflow. 🤔

**Comment by epilys** [comment]
Percentage is calculated here https://github.com/epilys/bb/blob/c903d4c2975509299fd3d2600a0c4c2102f445d0/src/components/kernel.rs#L575-L579

Seems like this happens when `time` is too big compared to `total_time.saturating_sub(previous_total_time)`
